<h1>Pivot Tables, Plots for PSNR, SSIM</h1>

In [1]:
from PIL import Image
from PIL import ImageFont
from PIL import ImageDraw
import sys
import os
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.pyplot import imshow
from PIL import Image
from IPython.display import display
%matplotlib inline

os.chdir('/Users/catherine/Documents/GANs_Research/my_imps/research_models/v3/evaluation')

In [2]:
import seaborn as sns
import pandas as pd

In [3]:
def table_to_df(csv, exp):
    df = pd.read_csv(csv)
    df.columns = ['num_label', 'value', 'file']
    df['exp'] = exp
    return df

<h1>PSNR</h1>

In [27]:
iris_pix2pixp = table_to_df('Iris/IR_GANB/psnr.csv', 'iris_pix2pix') #Iris pix2pix
EI_pix2pixp = table_to_df('Iris/EI_pix2pix/psnr.csv', 'EI_pix2pix') # EI pix2pix
EI_sensor_OGp = table_to_df('Iris/EI_sensor_OG/psnr.csv', 'EI_sensor_OG') #EI favtGAN baseline
EI_sensor_V3p = table_to_df('Iris/EI_sensor_V3/psnr.csv', 'EI_sensor_V3') #EI favtGAN no noise
EI_sensor_V4p = table_to_df('Iris/EI_sensor_V4/psnr.csv', 'EI_sensor_V4') #EI favtGAN noisy labels
EI_sensor_V5p = table_to_df('Iris/EI_sensor_V5/psnr.csv', 'EI_sensor_V5') #EI favtGAN Gaussian
IO_sensor_V4p = table_to_df('Iris/IO_sensor_V4/psnr.csv', 'IO_sensor_V4') #IO favtGAN noisy labels

In [28]:
final_p = iris_pix2pixp.append([EI_pix2pixp,
                              EI_sensor_OGp,
                              EI_sensor_V3p,
                              EI_sensor_V4p,
                              EI_sensor_V5p,
                              IO_sensor_V4p])
final_p

    num_label      value            file           exp
0           0  22.811803   Meng-1203.bmp  iris_pix2pix
1           1  21.890087   Meng-1212.bmp  iris_pix2pix
2           2  25.177855   Meng-1215.bmp  iris_pix2pix
3           3  25.133563   Meng-1218.bmp  iris_pix2pix
4           4  23.740118   Meng-1220.bmp  iris_pix2pix
..        ...        ...             ...           ...
93         93  23.194433  Vijay-1300.bmp  IO_sensor_V4
94         94  25.431627  Vijay-1303.bmp  IO_sensor_V4
95         95  24.924494  Vijay-1306.bmp  IO_sensor_V4
96         96  23.986705  Vijay-1310.bmp  IO_sensor_V4
97         97  25.682045  Vijay-1316.bmp  IO_sensor_V4

[686 rows x 4 columns]

In [29]:
# Maps to the Test IDs in IRIs

conditions = [
    (final_p['num_label'] >=0) & (final_p['num_label'] <= 31),
    (final_p['num_label'] >=32) & (final_p['num_label'] <= 64),
    (final_p['num_label'] >=65) & (final_p['num_label'] <= 97)

]
choices = ["Meng", "Vicki", "Vijay"]
final_p['subject']= np.select(conditions, choices, default='null')
print(final_p)

    num_label      value            file           exp subject
0           0  22.811803   Meng-1203.bmp  iris_pix2pix    Meng
1           1  21.890087   Meng-1212.bmp  iris_pix2pix    Meng
2           2  25.177855   Meng-1215.bmp  iris_pix2pix    Meng
3           3  25.133563   Meng-1218.bmp  iris_pix2pix    Meng
4           4  23.740118   Meng-1220.bmp  iris_pix2pix    Meng
..        ...        ...             ...           ...     ...
93         93  23.194433  Vijay-1300.bmp  IO_sensor_V4   Vijay
94         94  25.431627  Vijay-1303.bmp  IO_sensor_V4   Vijay
95         95  24.924494  Vijay-1306.bmp  IO_sensor_V4   Vijay
96         96  23.986705  Vijay-1310.bmp  IO_sensor_V4   Vijay
97         97  25.682045  Vijay-1316.bmp  IO_sensor_V4   Vijay

[686 rows x 5 columns]

In [30]:
final_p

    num_label      value            file           exp subject
0           0  22.811803   Meng-1203.bmp  iris_pix2pix    Meng
1           1  21.890087   Meng-1212.bmp  iris_pix2pix    Meng
2           2  25.177855   Meng-1215.bmp  iris_pix2pix    Meng
3           3  25.133563   Meng-1218.bmp  iris_pix2pix    Meng
4           4  23.740118   Meng-1220.bmp  iris_pix2pix    Meng
..        ...        ...             ...           ...     ...
93         93  23.194433  Vijay-1300.bmp  IO_sensor_V4   Vijay
94         94  25.431627  Vijay-1303.bmp  IO_sensor_V4   Vijay
95         95  24.924494  Vijay-1306.bmp  IO_sensor_V4   Vijay
96         96  23.986705  Vijay-1310.bmp  IO_sensor_V4   Vijay
97         97  25.682045  Vijay-1316.bmp  IO_sensor_V4   Vijay

[686 rows x 5 columns]

In [31]:
psnr_mean = pd.pivot_table(final_p,index=["exp"],values=["value"])
psnr_mean

                  value
exp
EI_pix2pix    23.945728
EI_sensor_OG  24.059560
EI_sensor_V3  21.999652
EI_sensor_V4  23.989818
EI_sensor_V5  22.082852
IO_sensor_V4  24.796782
iris_pix2pix  24.158099

In [32]:
psnr_mean_by_subject = pd.pivot_table(final_p,index=["subject", "exp"],values=["value"], aggfunc=[np.mean])
psnr_mean_by_subject

                           mean
                          value
subject exp
Meng    EI_pix2pix    23.846616
        EI_sensor_OG  23.970371
        EI_sensor_V3  21.888146
        EI_sensor_V4  23.873027
        EI_sensor_V5  21.986993
        IO_sensor_V4  24.732563
        iris_pix2pix  24.186740
Vicki   EI_pix2pix    24.113601
        EI_sensor_OG  24.276751
        EI_sensor_V3  22.250970
        EI_sensor_V4  24.208874
        EI_sensor_V5  22.306186
        IO_sensor_V4  24.960301
        iris_pix2pix  24.165264
Vijay   EI_pix2pix    23.873963
        EI_sensor_OG  23.928856
        EI_sensor_V3  21.856461
        EI_sensor_V4  23.884015
        EI_sensor_V5  21.952472
        IO_sensor_V4  24.695536
        iris_pix2pix  24.123161

In [33]:
def make_subjects(df):
    
    conditions = [
    (df['num_label'] >=0) & (df['num_label'] <= 31),
    (df['num_label'] >=32) & (df['num_label'] <= 64),
    (df['num_label'] >=65) & (df['num_label'] <= 97)]

    choices = ["Meng", "Vicki", "Vijay"]
    df['subject']= np.select(conditions, choices, default='null')

    return df

<h1>SSIM</h1>

In [34]:
iris_pix2pixs = table_to_df('Iris/IR_GANB/ssim.csv', 'iris_pix2pix') #Iris pix2pix
EI_pix2pixs = table_to_df('Iris/EI_pix2pix/ssim.csv', 'EI_pix2pix')# EI pix2pix
EI_sensor_OGs = table_to_df('Iris/EI_sensor_OG/ssim.csv', 'EI_sensor_OG') #EI favtGAN baseline
EI_sensor_V3s = table_to_df('Iris/EI_sensor_V3/ssim.csv', 'EI_sensor_V3') #EI favtGAN no noise
EI_sensor_V4s = table_to_df('Iris/EI_sensor_V4/ssim.csv', 'EI_sensor_V4') #EI favtGAN noisy labels
EI_sensor_V5s = table_to_df('Iris/EI_sensor_V5/ssim.csv', 'EI_sensor_V5') #EI favtGAN Gaussian
IO_sensor_V4s = table_to_df('Iris/IO_sensor_V4/ssim.csv', 'IO_sensor_V4') #IO favtGAN noisy labels

In [35]:
final_s = iris_pix2pixs.append([EI_pix2pixs,
                              EI_sensor_OGs,
                              EI_sensor_V3s,
                              EI_sensor_V4s,
                              EI_sensor_V5s,
                              IO_sensor_V4s])
final_s

    num_label     value            file           exp
0           0  0.667983   Meng-1203.bmp  iris_pix2pix
1           1  0.655792   Meng-1212.bmp  iris_pix2pix
2           2  0.675793   Meng-1215.bmp  iris_pix2pix
3           3  0.694411   Meng-1218.bmp  iris_pix2pix
4           4  0.690661   Meng-1220.bmp  iris_pix2pix
..        ...       ...             ...           ...
93         93  0.662779  Vijay-1300.bmp  IO_sensor_V4
94         94  0.711862  Vijay-1303.bmp  IO_sensor_V4
95         95  0.709449  Vijay-1306.bmp  IO_sensor_V4
96         96  0.695887  Vijay-1310.bmp  IO_sensor_V4
97         97  0.688552  Vijay-1316.bmp  IO_sensor_V4

[686 rows x 4 columns]

In [36]:
final_s = make_subjects(final_s)

In [37]:
ssim_mean = pd.pivot_table(final_s,index=["exp"],values=["value"], aggfunc=[np.mean])

In [38]:
ssim_mean_by_subject = pd.pivot_table(final_s,index=["subject", "exp"],values=["value"], aggfunc=[np.mean])

<h1>Summary</h1>

Table of all the metrics per image

In [39]:
final = final_s.merge(final_p, on=["file", "exp", "num_label", "subject"])
final.columns = ['image_num', 'ssim', 'image_file', 'exp', 'subj', 'psnr']
final = final[['image_num', 'ssim', 'image_file', 'exp', 'subj', 'psnr']]

In [40]:
def format_means(df, metric):
    foo = df.reset_index()
    foo.columns = foo.columns.droplevel(0)
    foo.columns = ['exp', '{}'.format(metric)]
    return foo

In [41]:
pm = psnr_mean.reset_index()
#moo.columns = moo.columns.droplevel(0)
pm.columns = ['exp', 'psnr']

sm = ssim_mean.reset_index()
sm.columns = sm.columns.droplevel(0)
sm.columns = ['exp', 'ssim']

means = sm.merge(pm, on='exp')

In [42]:
means

            exp      ssim       psnr
0    EI_pix2pix  0.681329  23.945728
1  EI_sensor_OG  0.682492  24.059560
2  EI_sensor_V3  0.652960  21.999652
3  EI_sensor_V4  0.682126  23.989818
4  EI_sensor_V5  0.651947  22.082852
5  IO_sensor_V4  0.690208  24.796782
6  iris_pix2pix  0.684641  24.158099